version: 2

project_name: icecast2mqtt

builds:
  - id: app
    main: ./cmd/app
    binary: icecast2mqtt
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}
      - -X main.author=SNMetamorph
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [tar.gz, zip]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - config.json.example
      - config.schema.json

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: '{{ .Tag }}'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  draft: true