FROM alpine:3.20

RUN apk add --no-cache ca-certificates && \
    addgroup -S app && adduser -S app -G app

WORKDIR /app

COPY icecast2mqtt /usr/local/bin/icecast2mqtt
COPY config.schema.json ./
COPY config.json.example ./
COPY LICENSE ./

USER app

CMD ["icecast2mqtt"]